# Initial example used: https://smarthomescene.com/diy/diy-presence-sensor-with-hi-link-ld2410-and-esp32-for-home-assistant/

# The LD2410 uses UART for communication
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  id: ld2410_uart

ld2410:
  id: ld2410_radar
  uart_id: ld2410_uart
  
binary_sensor:

  - platform: ld2410
    ld2410_id: ld2410_radar

    has_moving_target:
      name: Radar Moving Target
    
    has_still_target:
      name: Radar Still Target

    out_pin_presence_status:
      name: Radar Occupancy

sensor:
  - platform: ld2410
    ld2410_id: ld2410_radar

    detection_distance:
      name: Radar Detected Distance
      id: radar_detection_distance

#Configuration entities
number:
  - platform: ld2410
    ld2410_id: ld2410_radar

    timeout:
      name: Radar Occupancy Timeout
    
    max_move_distance_gate:
      name: Radar Max Move Distance
    
    max_still_distance_gate:
      name: Radar Max Still Distance
    

#Exposes control buttons
button:
  - platform: ld2410
    ld2410_id: ld2410_radar

    factory_reset:
      name: "Radar Factory Settings"
    restart:
      name: "Radar Reboot"
    query_params:
      name: "Radar Refresh Values"

#Radar firmware version
text_sensor:
  - platform: ld2410
    ld2410_id: ld2410_radar
    
    version:
      name: "Radar Firmware Version"
