i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a
  
sensor:
  - platform: bmp280
    i2c_id: bus_a
    address: 0x76 #0x77 # This might be different (test)
    update_interval: 15s
    iir_filter: 4x

    temperature:
      name: "Ambient Temperature"
      id: ambient_temperature
      oversampling: 16x
      device_class: temperature
    
    pressure:
      name: "Atmospheric Pressure"
      id: ambient_pressure
      device_class: atmospheric_pressure

  - platform: template
    name: "Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(bme280_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(ambient_pressure).state), 0.190234) - 1); // in meters
    update_interval: 15s
    icon: 'mdi:signal'
    unit_of_measurement: 'm'