# Allow importing this package
dashboard_import:
  package_import_url: "github://mariodivece/esphometemplates/standard/package-internaltemp.yaml@main"
  import_full_config: false

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    
