substitutions:
  # User-required substitutions
  device_site: "home"
  device_location_code: "office"
  device_location_name: "Office"
  device_type_code: "bullets3"
  device_type_name: "Bullet S3"
  device_number: "40126"
  device_ip: "10.16.40.126"

  # Project Substitutions (not intended for user substitution)
  device_model: "Bullet S3"
  device_make: "Bullet Automation"
  package_version: "2024.4.27"
  package_url: "github://mariodivece/esphometemplates/bullet-s3.yaml@main"

  log_level: INFO

  # Onboard RGB LED pin
  onboard_rgbled: GPIO21

  # Radar Pins
  radar_tx_pin: GPIO43
  radar_rx_pin: GPIO44
  
  # I2S Audio Output Pins
  audio_out_lrclk: GPIO06
  audio_out_bclk: GPIO05
  audio_out_dout: GPIO04

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Define Low voltage (3v3) i2c bus
i2c:
  id: i2c_bus_a
  sda: GPIO07
  scl: GPIO08
  scan: true

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - bullet-s3/board-esp32s3zero.yaml
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - standard/internaltemp.yaml
      - peripherals/onboard-rgbled.yaml
      - peripherals/radar-ld2410.yaml
      - peripherals/audio-out-i2s.yaml
      - peripherals/illuminance-bh1750.yaml
      - peripherals/ambient-bme680.yaml
      - peripherals/light-pwm.yaml
