substitutions:
  # User-required substitutions
  device_site: "home"
  device_location_code: "office"
  device_location_name: "Office"
  device_type_code: "bullets3"
  device_type_name: "Bullet S3"
  device_number: "40126"
  device_ip: "10.16.40.126"

  # Project Substitutions (not intended for user substitution)
  device_model: "Bullet S3"
  device_make: "Bullet Automation"
  package_version: "2024.4.27"
  package_url: "github://mariodivece/esphometemplates/bullet-s3.yaml@main"

  log_level: INFO

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - bullet-s3/board-esp32s3zero.yaml
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - standard/internaltemp.yaml
      