substitutions:
  usemac: "true"
  friendly: "Sonoff Switchman M5 3G US"
  uniquename: "switch-m5-3g"
  device_name: "M53G"
  device_make: "Sonoff"
  sw_version: "2024.2.8"
  loglevel: INFO

# Allow importing this package
dashboard_import:
  package_import_url: "github://mariodivece/esphometemplates/package-project.yaml@main"
  import_full_config: false

# Setup the integration and define some project variables
esphome:
  name: "${uniquename}"
  friendly_name: "${friendly}"
  comment: "${device_name} by ${device_make}"
  name_add_mac_suffix: ${usemac}
  min_version: "2023.2.0"
  project:
    name: "${device_make}.${device_name}"
    version: "${sw_version}"

# Enable logging
logger:
  level: "${loglevel}"