substitutions:
  apikey: !secret esp_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

# Allow importing this package
dashboard_import:
  package_import_url: "github://mariodivece/esphometemplates/package-wifi.yaml@main"
  import_full_config: false

# Enable Home Assistant API
api:
  encryption:
    key: "${apikey}"

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "Status"
    id: sensor_status

# Enable OTA
ota:
  safe_mode: true
  password: !secret ota_password

# Enable WiFi and AP for captive portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # password for hostspot is the same as password for net AP (needs captive_portal)
  ap:
    ssid: "${uniquename}-setup"
    password: "${wifi_password}"

captive_portal:
