substitutions:
  button_b_gpio: GPIO00
  button_n_gpio: ${button_b_gpio}
  button_n_name: "Button B"
  button_n_letter: b

# Allow importing this package
dashboard_import:
  package_import_url: "github://mariodivece/esphometemplates/package-sonoff-m5-button-a.yaml@main"
  import_full_config: false

packages:
  sonoff_m5_button:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - package-sonoff-m5-button.yaml
