substitutions:
  relay_c_gpio: GPIO22

# Allow importing this package
dashboard_import:
  package_import_url: "github://mariodivece/esphometemplates/package-sonoff-m5-relay-c.yaml@main"
  import_full_config: false

switch:
  # Physical GPIO Relay
  - platform: gpio
    name: "Relay C"
    pin: ${relay_c_gpio}
    id: relay_c
    restore_mode: RESTORE_DEFAULT_OFF