substitutions:
  button_n_gpio: GPIO04
  button_n_name: "Button A"
  button_n_letter: a

  # Button timing configurations
  filter_delay_on: 50ms
  filter_delay_off: 50ms

  # Single Click Timings
  timing_click_1: ON for at most 400ms
  timing_click_2: OFF for at least 600ms
  
  # Double Click Timings
  timing_double_click_1: ON for at most 500ms
  timing_double_click_2: OFF for at most 400ms
  timing_double_click_3: ON for at most 500ms
  timing_double_click_4: OFF for at least 250ms

  # Button Hold Timings
  timing_hold: ON for at least 1s

# Allow importing this package
dashboard_import:
  package_import_url: "github://mariodivece/esphometemplates/package-sonoff-m5-button.yaml@main"
  import_full_config: false

binary_sensor:

  # Physical Button
  - platform: gpio
    name: ${button_n_name}
    id: button_${button_n_letter}
    pin:
      number: ${button_n_gpio}
      mode: INPUT_PULLUP
      inverted: true

    filters:
      - delayed_on: ${filter_delay_on}
      - delayed_off: ${filter_delay_off}
    
    on_press:
      - if:
          condition:
            - lambda: 'return id(mode_${button_n_letter}).active_index() == 0;'
          then:
            - switch.toggle: relay_${button_n_letter}
      - if:
          condition:
            - lambda: 'return id(mode_${button_n_letter}).active_index() == 1;'
          then:
            - switch.turn_on: relay_${button_n_letter}

    on_release:
      - if:
          condition:
            - lambda: 'return id(mode_${button_n_letter}).active_index() == 1;'
          then:
            - switch.turn_off: relay_${button_n_letter}

    on_multi_click:
      # single click detection
      - timing:
        - ${timing_click_1}
        - ${timing_click_2}
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: ${button_n_letter}
                gesture: single_click

      # double click detection
      - timing:
          - ${timing_double_click_1}
          - ${timing_double_click_2}
          - ${timing_double_click_3}
          - ${timing_double_click_4}
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: ${button_n_letter}
                gesture: double_click

      # hold detection
      - timing:
          - ${timing_hold}
        then:
          - while:
              condition:
                binary_sensor.is_on: button_a
              then:
                - light.toggle: led_status
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: A${button_n_letter}
                      gesture: button_hold
                - delay: 100ms
          - light.turn_off: led_status