
substitutions:
  # User-required substitutions
  device_site: "bl24"
  device_location_code: "office"
  device_location_name: "Office"
  device_type_code: "audio"
  device_type_name: "Audio Player"
  device_number: "112"
  device_ip: "10.16.40.108"
  log_level: DEBUG

  # Project Substitutions (not intended for user substitution)
  device_model: "Player S3"
  device_make: "Bullet Automation"
  package_version: "2024.2.26"
  package_url: "github://mariodivece/esphometemplates/player-s3.yaml@main"

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - standard/internaltemp.yaml

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

i2s_audio:
  - id: i2s_bus_a
    i2s_lrclk_pin: 40
    i2s_bclk_pin: 42

media_player:
  - platform: i2s_audio
    id: audio_player
    name: Audio Player
    dac_type: external
    i2s_dout_pin: 41
    mode: mono
    on_pause:
      - media_player.stop
