# example taken from https://community.home-assistant.io/t/what-is-dashboard-import/422519/7
substitutions:
  name: yournamegoeshere
  apikey: enterencryptionkey
  loglevel: DEBUG
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  device_name: "Node32Sample"
  device_make: "BL24"
  sw_version: "2024.1.33"

esphome:
  name: "${name}"
  comment: "${device_name} by ${device_make}"
  name_add_mac_suffix: true
  min_version: "2023.2.0"
  project:
    name: "${device_make}.${device_name}"
    version: "${sw_version}"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://mariodivece/esphometemplates/scrapbook.yaml@main
  import_full_config: false

# Enable logging
logger:
  level: "${loglevel}"

# Enable Home Assistant API
api:
  encryption:
    key: "${apikey}"

# Enable OTA
ota:
  safe_mode: true
  password: !secret ota_password

# Enable WiFi and AP for captive portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Setup"
    password: "${wifi_password}"

captive_portal:
    
