substitutions:
  name: "sample-device-01"
  apikey: "6+jS7G8qNECQke9Yxw7zWgF9QfA2PN9qx1NuzMvAim8="

esphome:
  name: "${name}"
  name_add_mac_suffix: false

packages:
  BL24.Node32Sample:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    files: [scrapbook.yaml]
    refresh: 0d
