substitutions:
  usemac: "true"
  friendly: "My Sample Device 1"
  uniquename: "sample-device"

packages:
  somepackagename:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    files: [scrapbook.yaml]
    refresh: 0d
    
wifi:
  use_address: "192.168.1.11"
