substitutions:
  usemac: "false"
  friendly: "My Sample Device 1"
  uniquename: "my-sample-device-01"

packages:
  somepackagename:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    files: [scrapbook.yaml]
    refresh: 0s
    
wifi:
  use_address: "192.168.1.11"
