substitutions:
  usemac: "false"
  friendly: "My Sample Device 1"
  uniquename: "sample-device-798400"
  apikey: "JEkJZAWHGXHUHlmMrwiQKMsO/PytxwPF3eFHvMzwCMk="

packages:
  BL24.Node32Sample:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    files: [scrapbook.yaml]
    refresh: 0d
