substitutions:
  name: "sample-device-01"
  apikey: "6+jS7G8qNECQke9Yxw7zWgF9QfA2PN9qx1NuzMvAim8="

esphome:
  name: "${name}"
  name_add_mac_suffix: false

packages:
  BL24.Node32Sample: github://mariodivece/esphometemplates/scrapbook.yaml@main
