# example taken from https://community.home-assistant.io/t/what-is-dashboard-import/422519/7
substitutions:
  usemac: "true"
  friendly: "Friendly Name Goes Here"
  uniquename: "yournamegoeshere"
  loglevel: DEBUG
  apikey: !secret esp_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  device_name: "Node32Sample"
  device_make: "BL24"
  sw_version: "2024.1.36"

esphome:
  name: "${uniquename}"
  friendly_name: "${friendly}"
  comment: "${device_name} by ${device_make}"
  name_add_mac_suffix: ${usemac}
  min_version: "2023.2.0"
  project:
    name: "${device_make}.${device_name}"
    version: "${sw_version}"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://mariodivece/esphometemplates/scrapbook.yaml@main
  import_full_config: false

# Enable logging
logger:
  level: "${loglevel}"

# Enable Home Assistant API
api:
  encryption:
    key: "${apikey}"

# Enable OTA
ota:
  safe_mode: true
  password: !secret ota_password

# Enable WiFi and AP for captive portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${uniquename}-setup"
    password: "${wifi_password}"

captive_portal:

binary_sensor:
  - platform: gpio
    name: "Built-in Button"
    id: button
    pin: GPIO00
    inverted: True
    on_double_click:
      then:
        - light.toggle: light_output

light:
  - platform: monochromatic
    name: "Built-in LED"
    # This id must match the output id
    output: light_output

output:
  - id: light_output
    # ledc is the PWM platform for ESP32 chips.
    platform: ledc
    # Pin name for the built-in LED of my nodemcu-32s
    pin: GPIO2
    
