substitutions:
  name: "project-template"
  friendly_name: "Project Template"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  
  project:
    name: "builtin-led.bl24"
    version: "1.0.0"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "6+jS7G8qNECQke9Yxw7zWgF9QfA2PN9qx1NuzMvAim8="

ota:

dashboard_import:
  package_import_url: github://mariodivece/esphometemplates/scrapbook.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "bzGZ5pa4mPOk"

captive_portal:
    
