substitutions:
  # User-required substitutions
  device_site: "home"
  device_location: "bedroom01"
  device_location_name: "Bedroom 1"
  device_type: "4cpc"
  device_type_name: "4ch PWM Controller"
  device_number: "089"
  device_ip: "0.0.0.0"

  # Project Substitutions (not intended for user substitution)
  device_model: "RGBW2"
  device_make: "Shelly"
  sw_version: "2024.2.15"

  # Adjust package URL to point to this file
  package_url: "github://mariodivece/esphometemplates/shelly-rgbw2-4ch.yaml@main"

  # Diagnostics Substitutions
  loglevel: INFO
  timezone: "America/Mexico_City"

  # WiFi Substitutions
  apikey: !secret esp_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
  shelly_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - shelly-rgbw2/status-led.yaml
      - shelly-rgbw2/pwm-outputs.yaml
      - shelly-rgbw2/current-sensor.yaml
      - shelly-rgbw2/scripts-4ch.yaml

light:

  - platform: monochromatic
    name: "Channel 1 (R)"
    id: light_ch1
    output: pwm_out_ch1

  - platform: monochromatic
    name: "Channel 2 (G)"
    id: light_ch2
    output: pwm_out_ch2

  - platform: monochromatic
    name: "Channel 3 (B)"
    id: light_ch3
    output: pwm_out_ch3

  - platform: monochromatic
    name: "Channel 4"
    id: light_ch4
    output: pwm_out_ch4

binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: light_0_touch
    name: "I - Dimming Control"
    on_click:
      then:
        - if:
            condition:
              - light.is_off: ${device_name}_ch1
              - light.is_off: ${device_name}_ch2
              - light.is_off: ${device_name}_ch3
              - light.is_off: ${device_name}_ch4
            then:
              - light.turn_on:
                  id: ${device_name}_ch1
                  brightness: 1.0
              - light.turn_on:
                  id: ${device_name}_ch2
                  brightness: 1.0
              - light.turn_on:
                  id: ${device_name}_ch3
                  brightness: 1.0
              - light.turn_on:
                  id: ${device_name}_ch4
                  brightness: 1.0
            else:
              - light.turn_off: ${device_name}_ch1
              - light.turn_off: ${device_name}_ch2
              - light.turn_off: ${device_name}_ch3
              - light.turn_off: ${device_name}_ch4
    on_press:
      then:
        - if:
            condition:
              light.is_off: ${device_name}_ch1
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: light_0_touch
                  then:
                    - light.dim_relative:
                        id: ${device_name}_ch1
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_name}_ch2
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_name}_ch3
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_name}_ch4
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: light_0_touch
                      - light.is_on: ${device_name}_ch1
                  then:
                    - light.dim_relative:
                        id: ${device_name}_ch1
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_name}_ch2
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_name}_ch3
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_name}_ch4
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s