# ESPHome Firmware
# Sonoff D1 Dimmer
# Copyright (c) 2024 Mario Di Vece
# License: [MIT](https://opensource.org/license/mit/)
# Decription:
# Aims to provide a feature-rich, production-ready firmware for this compact
# and inexpensive device.
# For the below example, you need to keep the following entries in your secrets.yaml file:
#  - wifi_ssid: "<secret>"
#  - wifi_password: "<secret>"
#  - ota_password: "<secret>"
#  - esp_key: "<32-byte-base-64-secret>"
# 
# Example file (lab-office-dimr-003.yaml)
# 
# substitutions:
#  device_site: "lab"
#  device_location: "office"
#  device_location_name: "Office"
#  device_type: "dimr"
#  device_type_name: "Dimmer"
#  device_number: "004"
#  device_ip: "192.168.1.31"
#  level_min: "0"
#  level_max: "100"
#
# packages:
#   base_package:
#     url: https://github.com/mariodivece/esphometemplates/
#     ref: main
#     file: sonoff-d1.yaml
#     refresh: 0d
#

substitutions:
  # User-required substitutions
  device_site: "home"
  device_location: "bedroom01"
  device_location_name: "Bedroom 1"
  device_type: "wasw"
  device_type_name: "Wall Switch"
  device_number: "044"
  device_ip: "0.0.0.0"
  level_min: "0"
  level_max: "100"

  # Project Substitutions (not intended for user substitution)
  device_name: "D1"
  device_make: "Sonoff"
  sw_version: "2024.2.9"

  # Adjust package URL to point to this file
  package_url: "github://mariodivece/esphometemplates/sonoff-d1.yaml@main"

  # Diagnostics Substitutions
  loglevel: INFO
  timezone: "America/Mexico_City"

  # WiFi Substitutions
  apikey: !secret esp_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - standard/package-project.yaml
      - standard/package-diagnostics.yaml
      - standard/package-wifi.yaml

# Define the board for the compiler
esp8266:
  board: esp8285
  restore_from_flash: true

# D1 dimmer uses hardware serial port
# on the default pins @ 9600 bps to the chip
# that actually controls the dimmer and,
# optionally, the RF remote
uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

# And finally the light component
# gamma correction equal to zero gives linear scale,
# exactly what's needed for this device
light:
  - platform: sonoff_d1
    use_rm433_remote: false
    name: Brightness
    restore_mode: RESTORE_DEFAULT_OFF
    gamma_correct: 0.0
    default_transition_length: 0.75s
    min_value: ${level_min}
    max_value: ${level_max}
