# set button_letter: (A|B|C)
# set relay_gpio: example: GPIO23
# set button_gpio: example: GPIO04
select:
    # Config-only select for operation mode
  - platform: template
    name: "Mode - Button ${button_letter}"
    id: mode_${button_letter}
    icon: 'mdi:link-box-outline'
    entity_category: 'config'
    options:
      - "Toggle Relay"
      - "Sync Relay"
      - "Decoupled"
    initial_option: "Toggle Relay"
    optimistic: true
    set_action:
      - switch.turn_off: relay_${button_letter}

switch:
  # Physical GPIO Relay
  - platform: gpio
    name: "Relay ${button_letter}"
    pin: ${relay_gpio}
    id: relay_${button_letter}

binary_sensor:
  # Physical Button A
  - platform: gpio
    name: "Button ${button_letter}"
    id: button_${button_letter}
    pin:
      number: ${button_gpio}
      mode: INPUT_PULLUP
      inverted: true

    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    
    on_press:
      - if:
          condition:
            - lambda: 'return id(mode_${button_letter}).active_index() == 0;'
          then:
            - switch.toggle: relay_${button_letter}
      - if:
          condition:
            - lambda: 'return id(mode_${button_letter}).active_index() == 1;'
          then:
            - switch.turn_on: relay_${button_letter}

    on_release:
      - if:
          condition:
            - lambda: 'return id(mode_${button_letter}).active_index() == 1;'
          then:
            - switch.turn_off: relay_${button_letter}

    on_multi_click:
      # single click detection
      - timing:
        - ON for at most 400ms
        - OFF for at least 600ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: ${button_letter}
                gesture: single_click

      # double click detection
      - timing:
          - ON for at most 500ms
          - OFF for at most 400ms
          - ON for at most 500ms
          - OFF for at least 250ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: ${button_letter}
                gesture: double_click

      # hold detection
      - timing:
          - ON for at least 1s
        then:
          - while:
              condition:
                binary_sensor.is_on: button_${button_letter}
              then:
                - light.toggle: led_status
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: ${button_letter}
                      gesture: button_hold
                - delay: 100ms
          - light.turn_off: led_status
