# ESPHome Firmware
# Sonoff Switchman M5 1-Gang US
# Copyright (c) 2024 Mario Di Vece
# License: [MIT](https://opensource.org/license/mit/)
# Decription:
# Aims to provide a feature-rich, production-ready firmware for this elegant device
# - Provides Diagnostic data plus, status LED indicator when not connected to Home Assistant API
# - Relays may be configured individually on the UI to work in decoupled mode.
#   LEDs are physically connected to the relays, and they can't be individually controlled :(
# - Exposes gestures via events:
#   esphome.on_gesture { button: (A), gesture: (click|double_click|button_hold) }
# - Off-state (Background Brightness) of the LEDs is configurable via the UI
# 
# For the below example, you need to keep the following entries in your secrets.yaml file:
#  - wifi_ssid: "<secret>"
#  - wifi_password: "<secret>"
#  - ota_password: "<secret>"
#  - esp_key: "<32-byte-base-64-secret>"
# 
# Example file (sonoff-m5-1g-office-01.yaml)
# 
# substitutions:
#   usemac: "false"
#   friendly: "Sonoff M5 1G - Office Switch - 01"
#   uniquename: "sonoff-m5-1g-office-01"
# 
# packages:
#   base_package:
#     url: https://github.com/mariodivece/esphometemplates/
#     ref: main
#     files: [sonoff-m5-1g-us.yaml]
#     refresh: 0d
#   
# wifi:
#   use_address: "192.168.1.51"

# Basic substitutions (can be safely overriden)
substitutions:
  usemac: "true"
  friendly: "Sonoff Switchman M5 1G US"
  uniquename: "switch-m5-1g"
  loglevel: INFO
  timezone: "America/Mexico_City"
  apikey: !secret esp_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  device_name: "M51G"
  device_make: "Sonoff"
  sw_version: "2024.2.8"
  package_url: "github://mariodivece/esphometemplates/sonoff-m5-1g-us.yaml@main"

# Define the board for the compiler
esp32:
  board: esp32dev
  framework:
    type: arduino
      
# Setup the integration and define some project variables
esphome:
  name: "${uniquename}"
  friendly_name: "${friendly}"
  comment: "${device_name} by ${device_make}"
  name_add_mac_suffix: ${usemac}
  min_version: "2023.2.0"
  project:
    name: "${device_make}.${device_name}"
    version: "${sw_version}"

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Enable logging
logger:
  level: "${loglevel}"

# Enable Home Assistant API
api:
  encryption:
    key: "${apikey}"

# Enable OTA
ota:
  safe_mode: true
  password: !secret ota_password

# Enable WiFi and AP for captive portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # password for hostspot is the same as password for net AP (needs captive_portal)
  ap:
    ssid: "${uniquename}-setup"
    password: "${wifi_password}"

captive_portal:

time:
  - platform: sntp
    id: time_service
    timezone: ${timezone}

# Diagnostic output sensors
text_sensor:
  - platform: template
    name: "Deployment Version"
    lambda: return {"${sw_version}"};
    icon: "mdi:tag"
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      id: ip_address
      name: "IP Address"
      icon: "mdi:wan"

sensor:
  - platform: template
    id: internal_temp
    name: "Internal Temperature"
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    entity_category: diagnostic
    disabled_by_default: true
    lambda: return temperatureRead();

  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 90s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    id: sensor_uptime
    update_interval: 300s
    entity_category: "diagnostic"

# Operation Mode Configuration for Buttons
select:

    # Config-only select for operation mode
  - platform: template
    name: "Mode - Button A"
    id: mode_a
    icon: 'mdi:link-box-outline'
    entity_category: 'config'
    options:
      - "Toggle Relay"
      - "Sync Relay"
      - "Decoupled"
    initial_option: "Toggle Relay"
    optimistic: true
    set_action:
      - switch.turn_off: relay_a
    
# Provide a pre-built button for restarting the device
button:
  - platform: restart
    name: "Restart"
    id: button_restart

switch:
  # Physical indicator of the relay
  - platform: gpio
    id: led_a
    internal: true
    pin: GPIO19
    
  # Physical GPIO Relay
  - platform: gpio
    name: "Relay A"
    pin: GPIO23
    id: relay_a
    on_turn_on:
    - switch.turn_on: led_a
    on_turn_off:
    - switch.turn_off: led_a

output:
  # Physical GPIO PWM for off-state background brightness
  # This pin controls the background brightness for all LEDs
  # physically attached to the relays
  - platform: ledc
    id: pwm_output
    pin: GPIO18
    frequency: 1000 Hz
    
binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "Status"
    id: sensor_status

  # Make the status LED blink when not connected/trying to connect
  - platform: template
    name: "API connected"
    id: sensor_api_connected
    internal: true
    entity_category: 'diagnostic'
    device_class: 'connectivity'
    lambda: return global_api_server->is_connected();
    on_press:
      - light.turn_off: led_status
    on_release:
      - light.turn_on: led_status

  # Physical Button A
  - platform: gpio
    name: "Button A"
    id: button_a
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true

    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    
    on_press:
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 0;'
          then:
            - switch.toggle: relay_a
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_on: relay_a

    on_release:
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_off: relay_a

    on_multi_click:
      # single click detection
      - timing:
        - ON for at most 400ms
        - OFF for at least 600ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: A
                gesture: single_click

      # double click detection
      - timing:
          - ON for at most 500ms
          - OFF for at most 400ms
          - ON for at most 500ms
          - OFF for at least 250ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: A
                gesture: double_click

      # hold detection
      - timing:
          - ON for at least 1s
        then:
          - while:
              condition:
                binary_sensor.is_on: button_a
              then:
                - light.toggle: led_status
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: A
                      gesture: button_hold
                - delay: 100ms
          - light.turn_off: led_status

light:
  # Physical pin to the connection status LED
  # We don't expose this to the HA UI (internal)
  - platform: status_led
    name: "LED"
    id: led_status
    pin:
      number: GPIO05
      inverted: true
      ignore_strapping_warning: true
    internal: true
    restore_mode: RESTORE_DEFAULT_ON 

  # HA UI connection to the background brightness (PWM) pin
  - platform: monochromatic
    output: pwm_output
    name: "Background Brightness"
    restore_mode: RESTORE_DEFAULT_OFF
    icon: 'mdi:led-outline'
    entity_category: 'config'
