# ESPHome Firmware
# Sonoff Switchman M5 2-Gang US
# Copyright (c) 2024 Mario Di Vece
# License: [MIT](https://opensource.org/license/mit/)
# Decription:
# Aims to provide a feature-rich, production-ready firmware for this elegant device
# - Provides Diagnostic data plus, status LED indicator when not connected to Home Assistant API
# - Relays may be configured individually on the UI to work in decoupled mode.
#   LEDs are physically connected to the relays, and they can't be individually controlled :(
# - Exposes gestures via events:
#   esphome.on_gesture { button: (A|B), gesture: (click|double_click|button_hold) }
# - Off-state (Background Brightness) of the LEDs is configurable via the UI
# 
# For the below example to work, you need to keep the following entries in your secrets.yaml file:
#  - wifi_ssid: "<secret>"
#  - wifi_password: "<secret>"
#  - ota_password: "<secret>"
#  - esp_key: "<32-byte-base-64-secret>"
# 
# Example file (lab-office-wasw-003.yaml)
# 
# substitutions:
#  device_site: "lab"
#  device_location: "office"
#  device_location_name: "Office"
#  device_type: "wasw"
#  device_type_name: "Wall Switch"
#  device_number: "003"
#  device_ip: "192.168.1.31"
# 
# packages:
#   base_package:
#     url: https://github.com/mariodivece/esphometemplates/
#     ref: main
#     file: sonoff-m5-2g-us.yaml
#     refresh: 0d
#

substitutions:
  # User-required substitutions
  device_site: "home"
  device_location: "bedroom01"
  device_location_name: "Bedroom 1"
  device_type: "wasw"
  device_type_name: "Wall Switch"
  device_number: "044"
  device_ip: "0.0.0.0"

  # Project Substitutions (not intended for user substitution)
  device_name: "Switchman M5 (2-Gang)"
  device_make: "Sonoff"
  sw_version: "2024.2.9"

  # Adjust package URL to point to this file
  package_url: "github://mariodivece/esphometemplates/sonoff-m5-2g-us.yaml@main"

  # Diagnostics Substitutions
  loglevel: INFO
  timezone: "America/Mexico_City"

  # WiFi Substitutions
  apikey: !secret esp_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

  # Relay Configurations
  relay_a_gpio: GPIO23
  relay_b_gpio: GPIO19

  # Button Configurations
  button_a_gpio: GPIO04
  button_b_gpio: GPIO15

  # Indicator LED
  led_indicator_gpio: GPIO22

  # Button timing configurations
  filter_delay_on: 50ms
  filter_delay_off: 50ms

  # Single Click Timings
  timing_click_1: ON for at most 400ms
  timing_click_2: OFF for at least 600ms
  
  # Double Click Timings
  timing_double_click_1: ON for at most 500ms
  timing_double_click_2: OFF for at most 400ms
  timing_double_click_3: ON for at most 500ms
  timing_double_click_4: OFF for at least 250ms

  # Button Hold Timings
  timing_hold: ON for at least 1s

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - standard/package-project.yaml
      - standard/package-diagnostics.yaml
      - standard/package-wifi.yaml
      - standard/package-internaltemp.yaml
  sonoffm5_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - sonoff-m5/package-sonoff-m5-status-led.yaml
      - sonoff-m5/package-sonoff-m5-backlight.yaml
      - sonoff-m5/package-sonoff-m5-indicator-led.yaml
      - sonoff-m5/package-sonoff-m5-mode-button-a.yaml
      - sonoff-m5/package-sonoff-m5-mode-button-b.yaml
      - sonoff-m5/package-sonoff-m5-relay-a.yaml
      - sonoff-m5/package-sonoff-m5-relay-b.yaml
      - sonoff-m5/package-sonoff-m5-button-a.yaml
      - sonoff-m5/package-sonoff-m5-button-b.yaml

# Define the board for the compiler
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

switch:
    
  # Modify behavior of imported Relay A
  - id: !extend relay_b
    on_turn_on:
    - switch.turn_on: led_indicator
    on_turn_off:
    - switch.turn_off: led_indicator

binary_sensor:

  # Button A
  - id: !extend button_a
    on_press:
      # Toggle
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 0;'
          then:
            - switch.toggle: relay_a
      # Sync
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_on: relay_a

    on_release:
      # Sync
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_off: relay_a

  # Button B
  - id: !extend button_b
    on_press:
      # Toggle
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 0;'
          then:
            - switch.toggle: relay_b
      # Sync
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 1;'
          then:
            - switch.turn_on: relay_b
      # Momentary
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 2;'
          then:
            - switch.turn_on: relay_b
            - delay: 250ms
            - switch.turn_off: relay_b
      # Decoupled
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 3;'
          then:
            - switch.turn_on: led_indicator

    on_release:
      # Sync
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 1;'
          then:
            - switch.turn_off: relay_b
      # Decoupled
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 3;'
          then:
            - switch.turn_off: led_indicator
