substitutions:
  usemac: "false"
  friendly: "Sonoff M5 3G - Office Switch - 01"
  uniquename: "sonoff-m5-3g-office-01"

packages:
  base_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    files: [sonoff-m5-3g-us.yaml]
    refresh: 0d
