# ESPHome Firmware
# Sonoff Switchman M5 3-Gang US
# Copyright (c) 2024 Mario Di Vece
# License: [MIT](https://opensource.org/license/mit/)
# Decription:
# Aims to provide a feature-rich, production-ready firmware for this elegant device
# - Provides Diagnostic data plus, status LED indicator when not connected to Home Assistant API
# - Relays may be configured individually on the UI to work in decoupled mode.
#   LEDs are physically connected to the relays, and they can't be individually controlled :(
# - Exposes gestures via events:
#   esphome.on_gesture { button: (A|B|C), gesture: (click|double_click|button_hold) }
# - Off-state (Background Brightness) of the LEDs is configurable via the UI
# 
# For the below example, you need to keep the following entries in your secrets.yaml file:
#  - wifi_ssid: "<secret>"
#  - wifi_password: "<secret>"
#  - ota_password: "<secret>"
#  - esp_key: "<32-byte-base-64-secret>"
# 
# Example file (lab-office-wasw-003.yaml.yaml)
# 
# substitutions:
#  device_site: "lab"
#  device_location: "office"
#  device_location_name: "Office"
#  device_type: "wasw"
#  device_type_name: "Wall Switch"
#  device_number: "003"
#  device_ip: "192.168.1.223"
# 
# packages:
#   base_package:
#     url: https://github.com/mariodivece/esphometemplates/
#     ref: main
#     file: sonoff-m5-2g-us.yaml
#     refresh: 0d
#

substitutions:
  # User-required substitutions
  device_site: "lab"
  device_location: "office"
  device_location_name: "Office"
  device_type: "wasw"
  device_type_name: "Wall Switch"
  device_number: "003"
  device_ip: "192.168.1.223"

  # No user substitutions beyond this line
  usemac: "false"
  friendly: "${device_location_name} - ${device_type_name} - ${device_number}"
  uniquename: "${device_site}-${device_location}-${device_type}-${device_number}"

  # Adjust package URL to point to this file
  package_url: "github://mariodivece/esphometemplates/sonoff-m5-3g-us.yaml@main"

  # Project Substitutions
  device_name: "Switchman M5 (3-Gang)"
  device_make: "Sonoff"
  sw_version: "2024.2.8"

  # Diagnostics Substitutions
  loglevel: INFO
  timezone: "America/Mexico_City"

  # WiFi Substitutions
  apikey: !secret esp_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

  # Relay Configurations
  relay_a_gpio: GPIO23
  relay_b_gpio: GPIO19
  relay_c_gpio: GPIO22

  # Button Configurations
  button_a_gpio: GPIO04
  button_b_gpio: GPIO00
  button_c_gpio: GPIO15

  # Button timing configurations
  filter_delay_on: 50ms
  filter_delay_off: 50ms

  # Single Click Timings
  timing_click_1: ON for at most 400ms
  timing_click_2: OFF for at least 600ms
  
  # Double Click Timings
  timing_double_click_1: ON for at most 500ms
  timing_double_click_2: OFF for at most 400ms
  timing_double_click_3: ON for at most 500ms
  timing_double_click_4: OFF for at least 250ms

  # Button Hold Timings
  timing_hold: ON for at least 1s

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - standard/package-project.yaml
      - standard/package-diagnostics.yaml
      - standard/package-wifi.yaml
  sonoffm5_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - sonoff-m5/package-sonoff-m5-status-led.yaml
      - sonoff-m5/package-sonoff-m5-backlight.yaml
      - sonoff-m5/package-sonoff-m5-mode-button-a.yaml
      - sonoff-m5/package-sonoff-m5-mode-button-b.yaml
      - sonoff-m5/package-sonoff-m5-mode-button-c.yaml
      - sonoff-m5/package-sonoff-m5-relay-a.yaml
      - sonoff-m5/package-sonoff-m5-relay-b.yaml
      - sonoff-m5/package-sonoff-m5-relay-c.yaml
      - sonoff-m5/package-sonoff-m5-button-a.yaml
      - sonoff-m5/package-sonoff-m5-button-b.yaml
      - sonoff-m5/package-sonoff-m5-button-c.yaml

# Define the board for the compiler
esp32:
  board: esp32dev
  framework:
    type: arduino

binary_sensor:
  # Buttn A
  - id: !extend button_a
    on_press:
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 0;'
          then:
            - switch.toggle: relay_a
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_on: relay_a

    on_release:
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_off: relay_a

  # Button B
  - id: !extend button_b
    on_press:
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 0;'
          then:
            - switch.toggle: relay_b
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 1;'
          then:
            - switch.turn_on: relay_b

    on_release:
      - if:
          condition:
            - lambda: 'return id(mode_b).active_index() == 1;'
          then:
            - switch.turn_off: relay_b

  # Button C
  - id: !extend button_c
    on_press:
      - if:
          condition:
            - lambda: 'return id(mode_c).active_index() == 0;'
          then:
            - switch.toggle: relay_c
      - if:
          condition:
            - lambda: 'return id(mode_c).active_index() == 1;'
          then:
            - switch.turn_on: relay_c

    on_release:
      - if:
          condition:
            - lambda: 'return id(mode_c).active_index() == 1;'
          then:
            - switch.turn_off: relay_c  