substitutions:
  button_a_gpio: GPIO04

  # Button timing configurations
  filter_delay_on: 50ms
  filter_delay_off: 50ms

  # Single Click Timings
  timing_click_1: ON for at most 400ms
  timing_click_2: OFF for at least 600ms
  
  # Double Click Timings
  timing_double_click_1: ON for at most 500ms
  timing_double_click_2: OFF for at most 400ms
  timing_double_click_3: ON for at most 500ms
  timing_double_click_4: OFF for at least 250ms

  # Button Hold Timings
  timing_hold: ON for at least 1s
  timing_hold_repeat: 100ms

# Allow importing this package
dashboard_import:
  package_import_url: "github://mariodivece/esphometemplates/sonoff-m5/package-sonoff-m5-button-a.yaml@main"
  import_full_config: false

binary_sensor:
  # Physical Button A
  - platform: gpio
    name: "Button A"
    id: button_a
    pin:
      number: ${button_a_gpio}
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: false

    filters:
      - delayed_on: ${filter_delay_on}
      - delayed_off: ${filter_delay_off}
    
    on_multi_click:
      # single click detection
      - timing:
        - ${timing_click_1}
        - ${timing_click_2}
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: A
                gesture: single_click

      # double click detection
      - timing:
          - ${timing_double_click_1}
          - ${timing_double_click_2}
          - ${timing_double_click_3}
          - ${timing_double_click_4}
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: A
                gesture: double_click

      # hold detection
      - timing:
          - ${timing_hold}
        then:
          - while:
              condition:
                binary_sensor.is_on: button_a
              then:
                - light.toggle: led_status
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: A
                      gesture: button_hold
                - delay: ${timing_hold_repeat}
          - light.turn_off: led_status
